version: "3.8"

services:
  db:
    image: docker.devops.cambio.se/bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db